---
title: "fit_larkin"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fit_larkin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(larkin)
```

```{r data}
# Span
span <- 100

# Simulation
s <- sim(
  alpha = 2,
  beta = c(8, 6, 4, 2),
  init = rep(0.1, 8),
  p_bar = c(0.003, 0.917, 0.08),
  sigma = 0.1,
  burn = 100,
  span = span,
  harvest = 0.2,
  gamma = 0,
  x_phi = 0,
  extirp = 1e-6,
)

# Data list
data <- list(
  T = span,
  recruits = s$r_4,
  spawners = s$spawners,
  mu_alpha = 2,
  mu_beta = c(8, 6, 4, 2),
  mu_sigma = 0.5,
  sd_alpha = 0.5,
  sd_beta = 2,
  sd_sigma = 0.3,
  fudge = 1e-12
)

```

```{r fit}
# Only fit if cmdstan installed
if (!is.null(cmdstanr::cmdstan_version(error_on_NA = FALSE))) {
  # fit
  f1 <- fit(
    data = data,
    model = "larkin",
    chains = 1,
    step_size = 0.01,
    iter_warmup = 500,
    iter_sampling = 1000
  )
  
  f1$summary
}

```
