---
title: "forecast"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{forecast}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(larkin)
```

```{r arguments}
if (FALSE) {
  # Declare arguments for manual testing
  data <- larkin::chilko
  # index <- 67:68#61:68 # 61:68
  recruits <- "recruits"
  spawners <- "spawners"
  environs <- character(0)#c("flow", "pdo", "npgo_annual") # character(0)
  # timevary <- FALSE
  run_stan <- TRUE
  prior_mean_alpha <- 2
  prior_mean_beta <- c(-8, -6, -4, -2) # c(-4)
  prior_mean_gamma <- numeric(0)#rep(0, 3) # numeric(0)
  prior_mean_sigma <- 0.5
  prior_mean_omega <- 0#0.1 # 0
  prior_sd_alpha <- 0.25 * abs(prior_mean_alpha)
  prior_sd_beta <- 0.25 * abs(prior_mean_beta)
  prior_sd_gamma <- numeric(0)#rep(0.25, 3)
  prior_sd_sigma <- 0.25 * abs(prior_mean_sigma)
  prior_sd_omega <- 0#0.01 # 0
  id_cols <- c("stock_id", "stock_name", "brood_year") # NULL
  id_vals <- list(method = "model")
  cores <- ceiling(parallel::detectCores() / 2) # 4 # 1 # 4 # 1
  chains <- 3
  step_size <- 0.01
  adapt_delta <- 0.9
  iter_warmup <- 250
  iter_sampling <- 750 # 2000 # 750
}


```


```{r forecast}
if (FALSE) {
  output <- larkin::forecast(
    data = data,
    # index = index,
    recruits = recruits,
    spawners = spawners,
    environs = environs,
    # timevary = timevary,
    run_stan = run_stan,
    prior_mean_alpha = prior_mean_alpha,
    prior_mean_beta = prior_mean_beta,
    prior_mean_gamma = prior_mean_gamma,
    prior_mean_sigma = prior_mean_sigma,
    prior_mean_omega = prior_mean_omega,
    prior_sd_alpha = prior_sd_alpha,
    prior_sd_beta = prior_sd_beta,
    prior_sd_gamma = prior_sd_gamma,
    prior_sd_sigma = prior_sd_sigma,
    prior_sd_omega = prior_sd_omega,
    id_cols = id_cols,
    id_vals = id_vals,
    cores = cores,
    chains = chains,
    step_size = step_size,
    adapt_delta = adapt_delta,
    iter_warmup = iter_warmup,
    iter_sampling = iter_sampling
  )
  # View
  tibble::view(output$forecasts)
  tibble::view(output$lp__)
  tibble::view(output$alpha)
  tibble::view(output$beta)
  tibble::view(output$gamma)
  tibble::view(output$sigma)
  tibble::view(output$omega)
}



```
