---
title: "sim"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(larkin)
```

```{r simulate}
# Define
span <- 100
beta <- c(-8, -6, -4, -2)
gamma <- c(0.1, 0.2, 0.3)

# Define harvest control rule
lrp <- 0.001
usr <- 0.1
h_min <- 0
h_max <- 0.4
x <- seq(0, max(c(1, 1.1 * usr)), 0.001)
h <- harvest_control_rule(x = x, lrp = lrp, usr = usr, h_max = h_max)
hcr <- tibble::tibble(returns = x, h = h)
p1 <- ggplot2::ggplot(data = hcr, mapping = ggplot2::aes(x = returns, y = h)) +
  ggplot2::geom_line() +
  ggplot2::theme_bw() +
  ggplot2::theme(
    panel.grid.major = ggplot2::element_blank(), 
    panel.grid.minor = ggplot2::element_blank()
  )
p1

# Environmental covariates
environs <- simulate_environmental_covariates(span, rep(0, 3), 0.5, 1)

# Simulation
s <- sim(
  alpha = 2,
  beta = beta,
  init = rep(0.1, 8),
  p_bar = c(0.003, 0.917, 0.08),
  phi = 0,
  sigma = 0.1,
  burn = 100,
  span = span,
  lrp = lrp,
  usr = usr,
  h_min = h_min,
  h_max = h_max,
  gamma = gamma,
  environs = environs,
  extirp = 1e-6
)

# View
# tibble::view(s)

# Plot
p2 <- ggplot2::ggplot(
  data = s, 
  mapping = ggplot2::aes(x = time, y = spawners)
) +
  ggplot2::geom_line() +
  ggplot2::theme_bw() +
  ggplot2::theme(
    panel.grid.major = ggplot2::element_blank(), 
    panel.grid.minor = ggplot2::element_blank()
  )
p2

```
